### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by jishvi** [integer-net/solr-magento1#37]
I'm using Magento 1.9.3, Solr 6.6.2 and PHP7. Test connection was successful. But when I tried to index via command line I get this error.

`~/Documents/work/magentoapp$ php -f shell/indexer.php -- --reindex integernet_solr
Solr Search Index index process unknown error:
Apache_Solr_HttpTransportException: '400' Status: Bad Request in /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Apache_Solr/Service.php:381
Stack trace:
#0 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Apache_Solr/Service.php(730): Apache_Solr_Service->_sendRawPost('http://localhos...', '<add overwrite=...')
#1 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Apache_Solr/Service.php(830): Apache_Solr_Service->add('<add overwrite=...')
#2 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Apache_Solr/Service.php(787): Apache_Solr_Service->addRawDocuments('<doc><field nam...', false, true, true, 0)
#3 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Solr/Resource/ResourceFacade.php(277): Apache_Solr_Service->addDocuments(Array)
#4 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Solr/Indexer/IndexDocumentQueue.php(60): IntegerNet\Solr\Resource\ResourceFacade->addDocuments(1, Array)
#5 /home/jishnu/Documents/work/magentoapp/app/code/community/IntegerNet/Solr/Model/Bridge/LazyProductIterator.php(194): IntegerNet\Solr\Indexer\IndexDocumentQueue->flush(Object(IntegerNet_Solr_Model_Bridge_LazyProductIterator))
#6 /home/jishnu/Documents/work/magentoapp/app/code/community/IntegerNet/Solr/Model/Bridge/LazyProductIterator.php(104): IntegerNet_Solr_Model_Bridge_LazyProductIterator->validInner()
#7 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Solr/Indexer/ProductIndexer.php(506): IntegerNet_Solr_Model_Bridge_LazyProductIterator->valid()
#8 /home/jishnu/Documents/work/magentoapp/lib/IntegerNet_Solr/Solr/Indexer/ProductIndexer.php(147): IntegerNet\Solr\Indexer\ProductIndexer->_indexProductCollection(true, Object(IntegerNet_Solr_Model_Bridge_LazyProductIterator), 1, Array, Array)
#9 /home/jishnu/Documents/work/magentoapp/app/code/community/IntegerNet/Solr/Model/Indexer.php(193): IntegerNet\Solr\Indexer\ProductIndexer->reindex(NULL, true)
#10 /home/jishnu/Documents/work/magentoapp/app/code/community/IntegerNet/Solr/Model/Indexer.php(79): IntegerNet_Solr_Model_Indexer->_reindexProducts(NULL, true)
#11 /home/jishnu/Documents/work/magentoapp/app/code/core/Mage/Index/Model/Process.php(212): IntegerNet_Solr_Model_Indexer->reindexAll()
#12 /home/jishnu/Documents/work/magentoapp/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#13 /home/jishnu/Documents/work/magentoapp/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#14 /home/jishnu/Documents/work/magentoapp/shell/indexer.php(216): Mage_Shell_Compiler->run()
#15 {main}
`

**Comment by avstudnitz** [comment]
The `400` error means that some error occured inside Solr. Magento doesn't know which error this is. Please look up the exact error message in the Solr Admin in the "Logging" area and paste it here.

**Comment by jishvi** [comment]
`org.apache.solr.common.SolrException: ERROR: [doc=579_1] Error adding field 'product_returnable_i'='Yes' msg=For input string: "Yes"
    at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:240)
    at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)
    at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:922)
    at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
    at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
    at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
    at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
    at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
    at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
    at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
    at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:261)
    at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
    at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
    at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
    at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
    at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle(Server.java:534)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "Yes"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.apache.solr.schema.TrieField.createField(TrieField.java:620)
    at org.apache.solr.schema.TrieField.createFields(TrieField.java:681)
    at org.apache.solr.update.DocumentBuilder.addField(DocumentBuilder.java:72)
    at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:179)
    ... 49 more`

This is what I got

**Comment by avstudnitz** [comment]
Thanks, that helps. It tries to add a Yes/No attribute ("product_returnable") to Solr. If you have marked the attribute as "searchable", please remove that setting as it doesn't make any sense and is not supported. If it's not marked as searchable but as filterable (the other reason why it should be added to the solr index), it may be a bug in our code.

**Comment by jishvi** [comment]
Indexing worked when I changed "Used for Sorting in Product Listing" to no.

![image](https://user-images.githubusercontent.com/10036266/33437961-80e0113c-d60f-11e7-8965-6312e782a2b0.png)

**Comment by avstudnitz** [comment]
Very good.

**Comment by jishvi** [comment]
But now I'm getting this error when I search.

`PHP Fatal error:  Uncaught Error: Call to a member function getSortedChildren() on boolean in /home/jishnu/Documents/work/magentoapp/app/design/frontend/buildnext/green/template/catalog/layer/state.phtml:36\nStack trace:\n#0 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(3428): include()\n#1 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(3459): Mage_Core_Block_Template->fetchView('frontend/buildn...')\n#2 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(3473): Mage_Core_Block_Template->renderView()\n#3 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(2617): Mage_Core_Block_Template->_toHtml()\n#4 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(2335): Mage_Core_Block_Abstract->toHtml()\n#5 /home/jishnu/Documents/work/magentoapp/includes/src/__default.php(2279): Mage_Core_Block_Abstract->_getChildHtml('state', true)\n#6 /home/jishnu/Documents/work/magentoapp/includes/src/IntegerNet_Solr_Block_Result_Layer_View.php(69): Mage_Core_Block_Abstract->get in /home/jishnu/Documents/work/magentoapp/app/design/frontend/buildnext/green/template/catalog/layer/state.phtml on line 36, `

**Comment by avstudnitz** [comment]
Please open a new issue for a new problem.
There is probably a problem with your state.phtml. Try to reset that file to the default Magento file.

**Comment by avstudnitz** [comment]
Please open a new issue for a new problem.
There is probably a problem with your state.phtml. Try to reset that file to the default Magento file.

**Comment by jishvi** [comment]
Okay. Thanks for the help.
